# Generated by Django 3.0.7 on 2020-06-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=50)),
                ('currency_code', models.CharField(max_length=3, unique=True)),
                ('currency_value', models.FloatField()),
                ('currency_unit', models.FloatField()),
                ('currency_unification_unit', models.FloatField()),
            ],
        ),
    ]
